version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_data:
